### ISSUE TITLE
V2.0.1 - a couple of minor points

### ISSUE THREAD

**Issue by DerellLicht** [doug24/ThemeEditor#5]
Yes, TE V2.0.1 and dnGrep V4.1.47.0 are working beautifully now!!  Thank you again for all your efforts!

There are a few *very* minor issues that still exist in Theme Editor:

1. no About dialog, and no way to see version number??  Maybe version can just be added to title bar.

2. In 'Radio Group', there are two identical 'Disabled' items... is that intended??
   I think maybe one of those Disabled items is supposed to be checked, like the 'Check Group' does?

3. In the right-pane tab control (Sliders/Web/System/Theme/Sorted), the program always opens on Sliders,
   instead of remembering which tab I was previously on...
   I would like to start working from one of the other tabs by default - both System and Theme look interesting...
   but I'll probably never remember this intention, if the program always opens on Sliders...

4. actually, more generally, TE doesn't remember any 'current window' settings at all when re-started...
   Window size is not recovered, and I always have to adjust the pane positions, because the center pane overlaps the left (options) pane (see attached image) ...
   
Maybe you can take a look at these items at some point, but none of them are very critical.

![window pane overlap](https://github.com/doug24/ThemeEditor/assets/5551606/71e94368-f4d8-4336-968b-924f5c725629)

**Comment by doug24** [comment]
1. You're right, there is no About or version number - I'll add that sometime.

3. The radio group should have disabled both checked and unchecked. Here is what it looks like with the Dark theme - you probably want to check your setting for Radio.Disabled.OptionMark:
<img src="https://github.com/doug24/ThemeEditor/assets/17227248/23826b27-3473-44cd-b6af-bf04e425e5d3" width="400"/>

3 & 4. I haven't added any user settings, so no, it doesn't restore your last settings - I can do that sometime too.

**Comment by DerellLicht** [comment]
Okay, cool... I can see it now, yeah, the inner and outer rings were simply almost exactly the same color (black)...
Okay, item 2 is done.

However, I have an item 5 now:
5. on Theme tab, there is no direct way to set color for a field... 
Apparently, I need to click on the text of the item I want to modify (Radio.Disabled.OptionMark, in this case), then click on some other already-assigned color, to select the color for my selected item... there doesn't seem to be any color-selection option there... 
Unfortunately, all of the color-display fields on the bottom of that pane, are non-editable...
Shouldn't I be able to double-click on the color field, and get a standard Windows Color-selection dialog?

**Comment by doug24** [comment]
Yes, you first need to select the item you want to modify, and that will load the current color for the item in the sliders.  

For things like this, I've never found the Widows color selector very useful.  I usually use the hue - saturation - value sliders or pick one of the named colors and then adjust using HSV. 

But I guess I could add a color picker on another tab.

**Comment by DerellLicht** [comment]
> Yes, you first need to select the item you want to modify, and that will load the current color for the item in the sliders.
> 
> For things like this, I've never found the Windows color selector very useful. I usually use the hue - saturation - value sliders or pick one of the named colors and then adjust using HSV.
> 
> But I guess I could add a color picker on another tab.

hang on, lemme think... 
There are *no* sliders on the Theme tab... I think you're saying that I need to select the item that I want to edit, on the Theme tab, then switch over to the Sliders tab to actually set the color, do I parse this correctly??
That's probably doable, but it basically makes the Theme tab purposeless; I can select the item just as easily on the Sliders tab... 

I *think* what I should take from this, is that Sliders is the only one of those tabs that is actually developed; the others are all experiments, which haven't really been pursued in the real world... and in fact, that's really fine with me... Frankly, Theme Editor works beautifully for me as it is... no need to do alot of added work for things like this...

**Comment by DerellLicht** [comment]
BTW, what is advantage of HSV over RGB ??  I've always used the latter when setting desktop colors; I'm not at all familiar with HSV...

**Comment by doug24** [comment]
What I meant was select a named resource from the middle section, not the theme tab - that chooses the color resource to modify.  

The five tabs on the right all ways to modify the color of the selected resource - by sliders, by named colors, by system defined colors, by the other colors already used in the theme (Theme and Sorted).  Theme and Sorted are the same set of colors just ordered differently - and they get updated each time you commit a color change.  The System colors are not all that useful in this application because they change with the user's selected Windows color theme and in this application, they are used by value, not by named reference.  One other way to set/modify the color is to use the "Parse" text box below the sliders: you can enter an RGB or ARGB value as comma separated numbers (0-255) or hex values like 00FF00, FF00FF00 (with or without the # sign)>

The way I use the Theme and Sorted tabs is to copy colors from other elements - so for example, if I'm working on radio buttons, I might filter the Theme tab by "OptionMark" (checkbox) and use the same or similar colors for both radio buttons and checkboxes.  I will also filter the Sorted list by 'background' or "disabled" and see what colors have been used on other elements. The Sorted tab can also tell you what will be changed if you do a Synchronized color change by finding the color in the list for the element you are modifying and seeing what other elements also use that color.

One way I use the named colors is to help find the named resource in the sample controls:  Select a color resource in the middle, the set it to something extremely contrasting - like Red or Cyan.  For many of the named resources you have to move the mouse over, or press to see the color, but the Red or Cyan makes it much more obvious. Once you get what the named resource is for, just click the Revert color change button.

Note when making selections on the Theme and Sorted tabs to choose a color you may need to select another item and then reselect the color you want - the selection changes can be a bit strange.

HSV is just another way to represent a color value, like RGB.  But with HSV you can adjust the color keeping the same hue or keep the same color intensity and change to a different hue.  You can do the same things in RGB, but I find it much more difficult to fine tune the color in RGB. The best way to understand HSV is just experiment.  I usually set the hue first, then adjust the saturation and value.  Saturation of 0 is gray, you need to increase saturation to see the hue.  Value sets how dark or bright the color is.

"A" is the Alpha channel, or the transparency.  When you make semi-transparent colors the final color you see will be a combination of the color you are setting and the color that is below it.  I did publish a v2.0.2 that fixed an issue with transparency - previously when you adjusted the HSV sliders the transparency would get reset to 255.  In v2.0.2 the transparency is preserved when adjusting the HSV sliders.

**Comment by doug24** [comment]
Added the About dialog in [v2.0.3](https://github.com/doug24/ThemeEditor/releases/tag/v2.0.3)

I haven't done the save/restore settings yet.

**Comment by DerellLicht** [comment]
Looks good!!

**Comment by doug24** [comment]
Added save/restore the window size and location in new release [v2.0.4](https://github.com/doug24/ThemeEditor/releases/tag/v2.0.4).
